service: serverless-example

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x
  environment:
    PG_HOST: database-1.cacnfeqizyon.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: rs_aws_shop_db
    PG_USERNAME: postgres
    PG_PASSWORD: pq0#u#M76w86
functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

